insert into PRODUCTS (id, product_name, description, price, media_id) values (6, 'Tomatoes - Cherry, Yellow', 'Sugar - White Packet', 40, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (7, 'Chinese Foods - Chicken Wing', 'Bagel - Everything Presliced', 45, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (8, 'Lidsoupcont Rp12dn', 'Port - 74 Brights', 42, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (9, 'Bok Choy - Baby', 'Grenadillo', 32, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (10, 'Onion Powder', 'Seaweed Green Sheets', 50, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (11, 'Flower - Commercial Bronze', 'Gingerale - Schweppes, 355 Ml', 13, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (12, 'Chocolate Bar - Smarties', 'Daves Island Stinger', 48, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (13, 'Cheese - Swiss', 'Sesame Seed', 47, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (14, 'Lentils - Green, Dry', 'Pork - Liver', 49, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (15, 'Nut - Walnut, Chopped', 'Salmon Steak - Cohoe 6 Oz', 42, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (16, 'Trout - Smoked', 'Muffin - Bran Ind Wrpd', 22, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (17, 'Soup - Verve - Chipotle Chicken', 'Peas - Frozen', 48, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (18, 'Mace', 'Sauce - Mint', 32, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (19, 'Cheese - Pont Couvert', 'Flour - Strong Pizza', 50, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (20, 'Wine - Casillero Del Diablo', 'Ostrich - Fan Fillet', 49, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (21, 'Beef - Outside, Round', 'Coffee - Beans, Whole', 10, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (22, 'Tomatoes - Roma', 'Wine - Trimbach Pinot Blanc', 46, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (23, 'Wine - Pinot Grigio Collavini', 'Pork - Liver', 45, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (24, 'Pepper - Green', 'Pesto - Primerba, Paste', 33, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (25, 'Wine - Magnotta - Belpaese', 'Lid Tray - 12in Dome', 29, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (26, 'Burger Veggie', 'Veal - Loin', 19, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (27, 'Veal - Inside Round / Top, Lean', 'Mustard - Dry, Powder', 19, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (28, 'Flour - Chickpea', 'Wood Chips - Regular', 43, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (29, 'Salt - Table', 'Artichoke - Fresh', 24, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (30, 'Wasabi Powder', 'Lamb - Pieces, Diced', 10, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (31, 'Sea Bass - Fillets', 'Pepper - Green, Chili', 19, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (32, 'Cheese - Brie, Triple Creme', 'Yoplait Drink', 25, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (33, 'Beef - Bones, Marrow', 'Dip - Tapenade', 27, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (34, 'Straws - Cocktale', 'Nantucket - Kiwi Berry Cktl.', 33, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (35, 'Muffin - Mix - Mango Sour Cherry', 'Paper Cocktail Umberlla 80 - 180', 23, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (36, 'Cheese - Romano, Grated', 'Sauce - Thousand Island', 22, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (37, 'Cleaner - Pine Sol', 'Pepper - Yellow Bell', 48, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (38, 'Beef - Tongue, Cooked', 'Pineapple - Regular', 49, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (39, 'Pear - Halves', 'Curry Powder', 32, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (40, 'Energy Drink - Franks Pineapple', 'Avocado', 50, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (41, 'Longos - Chicken Wings', 'Cheese - Camembert', 37, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (42, 'Tea - Herbal Orange Spice', 'Pasta - Bauletti, Chicken White', 19, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (43, 'Ketchup - Tomato', 'Marsala - Sperone, Fine, D.o.c.', 45, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (44, 'Sparkling Wine - Rose, Freixenet', 'Coffee Cup 16oz Foam', 49, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (45, 'Versatainer Nc - 8288', 'Bacardi Breezer - Tropical', 41, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (46, 'Bagel - Plain', 'Cocoa Powder - Dutched', 44, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (47, 'Clam Nectar', 'Garbage Bags - Clear', 49, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (48, 'Cheese - Mozzarella, Buffalo', 'Yogurt - Blueberry, 175 Gr', 10, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (49, 'Berry Brulee', 'Jack Daniels', 46, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (50, 'Soup - Base Broth Beef', 'Apricots - Dried', 11, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (51, 'Flour - Buckwheat, Dark', 'Vinegar - White Wine', 47, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (52, 'Bonito Flakes - Toku Katsuo', 'Rum - Coconut, Malibu', 28, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (53, 'Oil - Truffle, Black', 'Mussels - Frozen', 14, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (54, 'Cookies - Amaretto', 'Juice - Lagoon Mango', 33, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (55, 'Worcestershire Sauce', 'Vermouth - Sweet, Cinzano', 25, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (56, 'Yeast Dry - Fermipan', 'Wine - Ruffino Chianti', 30, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (57, 'Wine - Red Oakridge Merlot', 'Tomatoes Tear Drop', 38, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (58, 'Mussels - Frozen', 'Black Currants', 18, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (59, 'Capers - Ox Eye Daisy', 'Papadam', 20, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (60, 'Shallots', 'Eggplant Oriental', 35, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (61, 'Pork - Tenderloin, Frozen', 'Lychee - Canned', 38, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (62, 'Tart Shells - Savory, 4', 'Beans - Butter Lrg Lima', 15, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (63, 'Cinnamon Rolls', 'Mint - Fresh', 17, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (64, 'Kellogs Cereal In A Cup', 'Lid Tray - 16in Dome', 16, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (65, 'Coffee - Egg Nog Capuccino', 'Basil - Dry, Rubbed', 22, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (66, 'Cup - 3.5oz, Foam', 'Chick Peas - Dried', 31, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (67, 'Chicken - Wieners', 'Tuna - Fresh', 31, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (68, 'Rappini - Andy Boy', 'Uniform Linen Charge', 33, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (69, 'Shrimp - 150 - 250', 'Uniform Linen Charge', 20, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (70, 'Melon - Watermelon Yellow', 'Juice - Tomato, 48 Oz', 25, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (71, 'Wine - Harrow Estates, Vidal', 'Artichoke - Hearts, Canned', 40, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (72, 'Pepper - Chili Powder', 'Chicken - Diced, Cooked', 27, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (73, 'Fish - Scallops, Cold Smoked', 'Mousse - Mango', 23, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (74, 'Zucchini - Mini, Green', 'Sausage - Blood Pudding', 22, 13);
insert into PRODUCTS (id, product_name, description, price, media_id) values (75, 'Cookies - Assorted', 'Shichimi Togarashi Peppeers', 26, 13);
